esphome:
  name: proxylora
  friendly_name: proxylora

esp32:
  # Usar la definición exacta para la Heltec Wifi LoRa 32 V2
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: "y"
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"
      CONFIG_XTAL_FREQ_26: 'y'

# Logger con puerto serie desactivado para no sobrecargar el procesador al escanear BLE
logger:

api:
  encryption:
    key: "GFPhWmjghhgk0fGxnidklkaDxZfC6eeVxVOkxlq1Ioo="
  on_client_connected:
    - esp32_ble_tracker.start_scan:
        continuous: true
  on_client_disconnected:
    if:
      condition:
        not:
          api.connected:
      then:
        - esp32_ble_tracker.stop_scan:

ota:
  - platform: esphome
    password: "018c4b14367ea8c624336f7d62a26060"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none 

  ap:
    ssid: "Proxy Fallback Hotspot"
    password: "teta1234"

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    continuous: false
    active: true
    interval: 320ms
    window: 300ms

bluetooth_proxy:
  active: true

safe_mode: 

esp32_ble_beacon:
  type: iBeacon
  uuid: fde3b150-2f64-43ba-aee9-867f75ee4a6f
  major: 1
  minor: 4
  min_interval: 500ms
  max_interval: 1000ms 
  
button:
  - platform: restart
    name: "Restart"
    entity_category: config

  - platform: safe_mode
    name: "Safe Mode"
    internal: false
    entity_category: config

sensor:
  - platform: uptime
    name: "Uptime"
    id: uptime_sensor
    entity_category: diagnostic
    internal: true

  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"